using Microsoft.Office.Interop.PowerPoint;
using Newtonsoft.Json;

namespace PowerPointStudio
{
    public class ezSlide
    {
        public string sid { get; set; }  //AutoGenerated slide id unique
        public ezShapes<ezShape> shapes = new ezShapes<ezShape>();
        public ezBackGround backGround;
        private static int slideCount=0;

        [JsonConstructor]
        public ezSlide()
        {

        }

        //With every ezSlide instance new sid will be created
        public ezSlide(Slide slide)
        {
            sid = "Slide" + slideCount;//slide id generation

            //Assigning ezShape to shapes
            foreach(Shape shape in slide.Shapes)
            {
                ezShape shp = new ezShape(shape);
                shapes.Add(shp);
            }

            backGround = new ezBackGround(slide);


            slideCount++;
            //Need to get background


        }
    }
}